apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kusama-mongodb-staging
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kusama-1kv-staging
  project: 1kv-backend-staging
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  source:
    repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    chart: mongodb
    targetRevision: ^15.1.4
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            architecture: standalone
            useStatefulSet: true

            auth:
              enabled: true
              rootPassword: <path:vaults/k8s-community-secrets/items/otv-kusama#mongo-root-password>
              username: <path:vaults/k8s-community-secrets/items/otv-kusama#mongo-username>
              password: <path:vaults/k8s-community-secrets/items/otv-kusama#mongo-password>
              database: <path:vaults/k8s-community-secrets/items/otv-kusama#mongo-db>

            directoryPerDB: true

            tls:
              enabled: false

            systemLogVerbosity: 0
            disableSystemLog: false

            resources:
              limits:
                cpu: 1600m
                memory: 6Gi
              requests:
                cpu: 400m
                memory: 2Gi

            persistence:
              enabled: true

            externalAccess:
              enabled: false

            arbiter:
              enabled: false
          
            metrics:
              enabled: true
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polkadot-mongodb-staging
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: polkadot-1kv-staging
  project: 1kv-backend-staging
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  source:
    repoURL: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    chart: mongodb
    targetRevision: ^15.1.4
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            architecture: standalone
            useStatefulSet: true

            auth:
              enabled: true
              rootPassword: <path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-root-password>
              username: <path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-username>
              password: <path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-password>
              database: <path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-db>

            directoryPerDB: false

            tls:
              enabled: false

            systemLogVerbosity: 0
            disableSystemLog: false

            resources:
              limits:
                cpu: 1600m
                memory: 6Gi
              requests:
                cpu: 400m
                memory: 2Gi

            persistence:
              enabled: true

            externalAccess:
              enabled: false

            arbiter:
              enabled: false

            metrics:
              enabled: true
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
